In [2]:
import numpy as np

In [ ]:
# python array using numpy
arr_1d=np.array([1,2,3])
print(arr_1d)
arr_2d=np.array([[1,2,3],[2,3,5]])
print(arr_2d)
arr_3d=np.array([[1,2,3],[2,5,3],[34,3,2]])
print(arr_3d)

[1 2 3]
[[1 2 3]
 [2 3 5]]
[[ 1  2  3]
 [ 2  5  3]
 [34  3  2]]


In [8]:
# numpy array and python array
py_list=[1,2,4]
print("Python X ",py_list * 2)
np_array=np.array([1,2,3])
print("Numpy X ",np_array * 3)

Python X  [1, 2, 4, 1, 2, 4]
Numpy X  [3 6 9]


In [10]:
import time as t
start= t.time()
py_mul=[i*2 for i in range(1000000)]
print("Python takes ",t.time()-start)

start1 =t.time()
np_array=np.arange(10000000)*2
print("Numpy takes ",t.time()-start1)

Python takes  0.1184396743774414
Numpy takes  0.05750393867492676


In [20]:
# creating array in numpy
zeros=np.zeros((2,3))
print("Zeros Matrix\n",zeros)
ones=np.ones((2,4))
print("Ones Matrix\n",ones)
full=np.full((2,3),7)
print("full Array\n", full)

Zeros Matrix
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full Array
 [[7 7 7]
 [7 7 7]]


In [25]:
random= np.random.random((4,5))
print("Random Matrix\n",random)
sequence=np.arange(0,10,2)
print("Sequence Array\n",sequence)

Random Matrix
 [[0.17540719 0.79669476 0.55340055 0.77197448 0.01685646]
 [0.18931818 0.17003176 0.74610116 0.34478939 0.27562161]
 [0.67125637 0.13720844 0.35393879 0.63669561 0.41091598]
 [0.65369211 0.79577774 0.08999495 0.19158381 0.71988566]]
Sequence Array
 [0 2 4 6 8]


In [ ]:
# vector, matrix and tensor(no. of array)
vector= np.array([1,2,3])
print("Vector\n",vector)
matrix=np.matrix([[1,2,3,4],[3,4,5,2],[24,5,6,3]])
print("Matrix\n" , matrix)

tensor=np.array([[[1,2],[3,4]],[[4,3],[6,9]]])
print("Tensor\n",tensor)

Vector
 [1 2 3]
Matrix
 [[ 1  2  3  4]
 [ 3  4  5  2]
 [24  5  6  3]]
Tensor
 [[[1 2]
  [3 4]]

 [[4 3]
  [6 9]]]


In [3]:
# array properties
arr=np.array([[1,2,3],[3,45,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Datatype",arr.dtype )
arr1=np.array([[[1,2],[3,4]],[[4,3],[6,9]]])
print("Shape",arr1.shape)
print("Dimension",arr1.ndim)
print("Datatype",arr1.dtype )

Shape (2, 3)
Dimension 2
Datatype int64
Shape (2, 2, 2)
Dimension 3
Datatype int64


In [18]:
#  array reshaping
arr=np.arange(12)
print("Original Array\n", arr)
reshaped= arr.reshape(4,3)


# here the .reshape will modify the original array in different order
print("Reshaped\n",reshaped)
flattened=reshaped.flatten()
# it will stretch out the array in 1d array. it works on copy
print("Flattened\n",flattened)
print(reshaped)
raveled=reshaped.ravel()
# it works on main copy
print("Reveled\n",raveled)
print(reshaped)
transpose= reshaped.T
print("Transposed\n", transpose)


Original Array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Reveled
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Transposed
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [16]:
arr = np.arange(12)
reshaped = arr.reshape(4, 3)

flattened = reshaped.flatten()
raveled = reshaped.ravel()

# Modify both
flattened[0] = 999
raveled[1] = 888

print("Original array:\n", arr)
print("Reshaped array:\n", reshaped)
print("Flattened array:\n", flattened)
print("Raveled array:\n", raveled)


Original array:
 [  0 888   2   3   4   5   6   7   8   9  10  11]
Reshaped array:
 [[  0 888   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
Flattened array:
 [999   1   2   3   4   5   6   7   8   9  10  11]
Raveled array:
 [  0 888   2   3   4   5   6   7   8   9  10  11]
