### Numpy Array Operation



In [1]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4,4,5,5])
print("ARRAY\n", arr)
print("BASIC SLICING\n", arr[:])
print("BASIC SLICING\n", arr[::2])
print("BASIC SLICING\n", arr[::-1])

ARRAY
 [1 2 3 4 4 5 5]
BASIC SLICING
 [1 2 3 4 4 5 5]
BASIC SLICING
 [1 3 4 5]
BASIC SLICING
 [5 5 4 4 3 2 1]


In [10]:
arr_2d=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
print("2d ARRAY \n",arr_2d)
print("Specific Element: ",arr_2d[1,2])
print("Specific Element: ",arr_2d[:,2])
print("2d ARRAY SLICING \n",arr_2d[::])
print("2d ARRAY SLICING \n",arr_2d[::-2])

2d ARRAY 
 [[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]
Specific Element:  4
Specific Element:  [3 4 6]
2d ARRAY SLICING 
 [[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]
2d ARRAY SLICING 
 [[4 5 6 7]
 [1 2 3 4]]


# Sorting

In [24]:
unsorted=np.array([3,42,5,6])
print("Sorted Array\n", np.sort(unsorted))

arr_2d_unsorted=np.array([[1,23,5],[13,4,7],[12,17,2]])
print("Array 2D\n", arr_2d_unsorted)
print("After Sorted via column \n",np.sort(arr_2d_unsorted,axis=0))
print("After Sorted via row \n",np.sort(arr_2d_unsorted,axis=1))

Sorted Array
 [ 3  5  6 42]
Array 2D
 [[ 1 23  5]
 [13  4  7]
 [12 17  2]]
After Sorted via column 
 [[ 1  4  2]
 [12 17  5]
 [13 23  7]]
After Sorted via row 
 [[ 1  5 23]
 [ 4  7 13]
 [ 2 12 17]]


## Filter

In [29]:
num= np.array([1,3,6,2,7,8])
print("Array\n",num)
print("Even no. in Array\n",num[num %2==0]) #Since this is numpy , it provides us flexibility to use expressions in '...' at arr[...] which helps to find the even or odd no. in array directly 


Array
 [1 3 6 2 7 8]
Even no. in Array
 [6 2 8]


## Filter with Mask

In [31]:
mask=num>5 
print("Numbers greater than 5 ", num[mask])
print("Numbers greater than 5 ", num[num<8])

Numbers greater than 5  [6 7 8]
Numbers greater than 5  [1 3 6 2 7]


## Fancy indexing vs np.where()

In [33]:
indices=[0,3,4]
print(num[indices])
where_result=np.where(num>4)
print(num[where_result])

[1 2 7]
[6 7 8]


In [36]:
condition_array=np.where(num>5,num*3,num) # based on the true condition it returns 2nd arg else 3rd and checks each of element
print("Condition Array\n",condition_array)

Condition Array
 [ 1  3 18  2 21 24]


## Adding data and removing it

In [42]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,3,3,24])
print(arr1+arr2)  #normal addition operation
combined=np.concatenate((arr1,arr2))  # combining both array
print(combined)

[ 5  5  6 28]
[ 1  2  3  4  4  3  3 24]


## Array Compatible

In [46]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,12,30])
arr3=np.array([1,2,23,42])
print("Compatible Test\n", arr1.shape==arr2.shape)

Compatible Test
 False


In [ ]:
arr=np.array([1,7,5])
print("Original Array\n",arr)
new_row=np.array([1,2,3])
with_new_data=np.vstack((arr,new_row)) #vstack adds new row
print("With New data Array\n",with_new_data)

arr1=np.array([[1,2],[2,3],[4,7]])
print("Oringinal Array\n",arr1)
new_column=np.array([[1],[3],[7]])
with_new_data=np.hstack((arr1,new_column)) #hstack adds new column
print("With New data Array\n",with_new_data)

Original Array
 [1 7 5]
With New data Array
 [[1 7 5]
 [1 2 3]]
Oringinal Array
 [[1 2]
 [2 3]
 [4 7]]
With New data Array
 [[1 2 1]
 [2 3 3]
 [4 7 7]]


In [53]:
arr=np.array([1,2,3,4,5])
print("Before Deletion Array\n",arr)
new_array=np.delete(arr,3)
print("Array after deletion\n",new_array)

Before Deletion Array
 [1 2 3 4 5]
Array after deletion
 [1 2 3 5]
